Jep/verification
kieler/semantics pull request #67
Opened 2022-10-13 13:25 UTC by Drakae

LanguageServerExtension for Model Checking

2022-10-13 14:26 UTC, a-sr commented on plugins/de.cau.cs.kieler.verification/META-INF/MANIFEST.MF
> + org.eclipse.lsp4j.jsonrpc;bundle-version="0.10.0",
Non-IDE plugin must not depend on LSP stuff.

2022-10-13 14:28 UTC, a-sr commented on plugins/de.cau.cs.kieler.verification/META-INF/MANIFEST.MF
> + de.cau.cs.kieler.simulation.ide;bundle-version="1.3.0",
Non-IDE plugin must not depend on IDE plugin. This is the reason for the failed build.
Proper review will follow later.

2022-10-14 08:18 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.language.server/run-configurations/LanguageServer with KLighD in Workspace.launch
> +    <booleanAttribute key="org.eclipse.debug.core.ATTR_FORCE_SYSTEM_CONSOLE_ENCODING" value="false"/>
Do you know why this was added?

2022-10-14 08:19 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.language.server/run-configurations/LanguageServer with KLighD in Workspace.launch
> +        <listEntry value="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#10;&lt;runtimeClasspathEntry externalArchive=&quot;/de.cau.cs.kieler.formats&quot
It does not matter whether this is an internal or external archive. Just to understand this change better: I guess you do not have kieler.formats open in your workspace, correct?

2022-10-14 08:21 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.language.server/src/de/cau/cs/kieler/language/server/KeithLanguageClient.xtend
> +    def void sendVerificationProperties(Object props, String dummy)
Why is this necessary? Why can't you add the correct type here?

2022-10-14 08:21 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.simulation.ide/META-INF/services/de.cau.cs.kieler.language.server.ILanguageServerContribution
> +de.cau.cs.kieler.simulation.ide.language.server.SimulationLanguageServerContribution
Why the empty line?

2022-10-14 08:32 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification.ide/src/de/cau/cs/kieler/verification/ide/language/server/VerificationCommandExtension.xtend
> +    @JsonNotification('loadProperties')
The convertion is to use `load-properties` rather than `loadProperties`. Also check this for other messages.

2022-10-14 08:32 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification.ide/src/de/cau/cs/kieler/verification/ide/language/server/VerificationLanguageServerContribution.xtend
> + * Copyright 2019 by
Wrong year.

2022-10-14 08:32 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification.ide/src/de/cau/cs/kieler/verification/ide/language/server/VerificationLanguageServerExtension.xtend
> + * Copyright ${year} by
Wrong year

2022-10-14 08:33 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification.ide/src/de/cau/cs/kieler/verification/ide/language/server/VerificationLanguageServerExtension.xtend
> +    protected KeithLanguageClient client
Please add a new line here

2022-10-14 08:35 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/META-INF/MANIFEST.MF
> + org.eclipse.xtext;bundle-version="2.25.0",
Are these versions required? Otherwise please remove them.

2022-10-14 08:36 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/src/de/cau/cs/kieler/verification/SmallVerificationProperty.xtend
> + * Copyright ${year} by
Add year.

2022-10-14 08:36 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/src/de/cau/cs/kieler/verification/SmallVerificationProperty.xtend
> + * A reduced version of VerifcationProperty. It is used to send properties to the client.
Typo

2022-10-14 08:36 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/src/de/cau/cs/kieler/verification/VerificationLogic.xtend
> + * Copyright ${year} by
Year

2022-10-14 08:37 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/src/de/cau/cs/kieler/verification/VerificationLogic.xtend
> +    // TODO: save/get the options without IPreferenceStore
Is this still necessary? Otherwise remove.

2022-10-14 08:37 UTC, soerendomroes commented on plugins/de.cau.cs.kieler.verification/src/de/cau/cs/kieler/verification/VerificationPropertyIDGenerator.xtend
> + * Copyright ${year} by
Year

2022-10-14 11:02 UTC, Drakae commented on plugins/de.cau.cs.kieler.language.server/run-configurations/LanguageServer.launch
> +    <booleanAttribute key="org.eclipse.debug.core.ATTR_FORCE_SYSTEM_CONSOLE_ENCODING" value="false"/>
No

2022-10-17 06:52 UTC, soerendomroes approved these changes

2022-10-17 15:11 UTC, a-sr requested changes
I left a few minor change requests and comments.
Overall, nice work!

2022-10-18 07:40 UTC, a-sr approved these changes

2022-10-18 07:48 UTC, merged