Proxy Views: SCCharts-specific renderings
kieler/semantics pull request #81
Opened 2023-03-02 14:15 UTC by NiklasRentzCAU

supersedes #54 
Dependency on kieler/KLighD#129

2023-03-03 12:42 UTC, Eddykasp requested changes

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/ControlflowRegionSynthesis.xtend
> +        val minSize = 10
magic number, should be const defined somewhere

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/ControlflowRegionSynthesis.xtend
> +        val bigEnough = proxyBounds.width > minSize && proxyBounds.height > minSize
rename to isBigEnough for clarity

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/DataflowRegionSynthesis.xtend
> +                    setProperty(KlighdProperties.PROXY_VIEW_RENDER_NODE_AS_PROXY, false)
see above comment

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/DataflowRegionSynthesis.xtend
> +        val minSize = 10
magic number repetition

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/DataflowRegionSynthesis.xtend
> +        val bigEnough = proxyBounds.width > minSize && proxyBounds.height > minSize
code duplication

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +        val maxProxyLabelLength = 5
code duplication / magic number

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +            )
currently we don't actually use any of this info, so we should consider whether we really want it taking up space

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +                }
this doesn't add anything and should maybe be reverted for conciseness

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +                    setProperty(KlighdProperties.PROXY_VIEW_RENDER_NODE_AS_PROXY, false)
see above comment about comments

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +            val minSize = 10
magic number

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +            val bigEnough = proxyBounds.width > minSize && proxyBounds.height > minSize
code duplication

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/filtering/SCChartsSemanticFilterTags.java
> +    }
again, do we want all these number value tags at the moment if we don't use them?

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/styles/ControlflowRegionStyles.xtend
> +                    setProperty(KlighdProperties.IS_NODE_TITLE, true)
this should be replaced with a semantic tag

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/styles/StateStyles.xtend
> +    public static final int DEFAULT_FIGURE_MIN_NODE_SIZE = 34; // 2 x corner radius
2 * DEFAULT_FIGURE_CORNER_RADIUS

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.scg.klighd/src/de/cau/cs/kieler/scg/klighd/SCGraphDiagramSynthesis.xtend
> +
unnecessary newline

2023-03-03 12:42 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.scg.klighd/src/de/cau/cs/kieler/scg/klighd/SCGraphDiagramSynthesis.xtend
> +
unnecessary newline

2023-03-03 15:10 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/ControlflowRegionSynthesis.xtend
> +        val minSize = 10
Open from previous PR:
Question: "where do these values come from, how are they chosen and what do they control?"
tik answer: "I chose those values myself and tested out when the original proxy bounds would be appropriately large enough. It's needed in case there's no text or the text doesn't exceed the chosen threshold size - as the proxy might be barely visible in these cases. Doing this allows for non-square proxies"

2023-03-03 15:17 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/ControlflowRegionSynthesis.xtend
> +        val maxProxyLabelLength = 5
comment from old PR:
tik: "5 is a good compromise of cutting as the proxies aren't too wide and usually 5 characters suffice for uniquely identifying the corresponding node
Also fun fact: in English, the average word length is about 5 or less https://www.researchgate.net/figure/Average-word-length-in-the-English-language-Different-colours-indicate-the-results-for_fig1_230764201 "

2023-03-03 15:18 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/DataflowRegionSynthesis.xtend
> +        val maxProxyLabelLength = 5
from previous PR:
magic number, should probably be the same as in the control flow region synthesis.

2023-03-03 15:21 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/styles/ControlflowRegionStyles.xtend
> +    }
This method seems to be not needed, as it was solved from the previous PR using a lambda.

2023-03-03 15:28 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/styles/ControlflowRegionStyles.xtend
> +    def KRendering addProxyRegion(KContainerRendering container, List<Pair<? extends CharSequence, TextFormat>> label) {
Some of this proxy code seems to be copied from the non-proxy renderings and might therefore duplicate code (not well visible in the PR diff) and should be checked as well.

2023-03-07 10:26 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/ControlflowRegionSynthesis.xtend
> +                    setProperty(KlighdProperties.PROXY_VIEW_RENDER_NODE_AS_PROXY, false)
If this is a semantic filtering option that is on by default that would be fine as well. Allows the user to configure it with the same default behavior.

2023-03-07 10:34 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/StateSynthesis.xtend
> +            )
right, this is more data that is sent for each state, even if it never used. I guess leaving the code in, but commented out would be fine if we were to reactivate this semantic information in some way again. The other current thesis for structure-based editing using semantic tags seems to use different ones: https://github.com/kieler/semantics/compare/master...FelixJoehnk:semantics:master

2023-03-07 10:42 UTC, NiklasRentzCAU commented on plugins/de.cau.cs.kieler.sccharts.ui/src/de/cau/cs/kieler/sccharts/ui/synthesis/styles/ControlflowRegionStyles.xtend
> +                    setProperty(KlighdProperties.IS_NODE_TITLE, true)
I wouldn't replace it - We need this (or a) non-semantic property to configure the potential title scaling of this title. A further semantic tag could state, if it is a node title in general, which we would not use currently.

In general I am not quite sure yet if we want to tag many different semantic information in general and be able to use it on the client, even if we don't currently, or if that should be implemented on demand. Many tags will always blow up the model and with that the data sent for the diagram generation.

2023-03-07 14:05 UTC, Eddykasp approved these changes

2023-03-15 13:49 UTC, Eddykasp commented
remove "filter" from filter names @Eddykasp

2023-06-20 13:50 UTC, Eddykasp commented
One thing that I noticed when looking at proxies in different contexts, was that it is sometimes hard to differentiate proxies from normal nodes. In some cases this makes them less helpful so it could be sensible to make proxy-specific rendering look slightly different than regular nodes, for example in colour. Something we should consider when developing proxies for other/new diagram types.

2024-05-07 14:20 UTC, a-sr approved these changes
Ok

2024-05-07 14:20 UTC, merged